import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/shared/navbar/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased bg-gray-lightest dark:bg-gray-darkest dark:text-gray-lightest transition-colors`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}

{
  /* <div className="flex gap-2">
        <Switch onCheckedChange={toggleViewMode} />
        <label>
          {viewMode === "list" ? "Switch to Grid View" : "Switch to List View"}
        </label>
      </div> */
}
